[package]
name = "locus"
version = "0.2.0"
entry = "src/service.ts"
language = "0.3"

[compiler]
backend = "scriptc"

[deployment]
default_network = "local"

[networks.local]
kind = "minijam"
deployment_rpc = "http://127.0.0.1:8080"
node_rpc = "http://127.0.0.1:9944"
backend_rpc = "http://127.0.0.1:8090"
genesis_hash = "0xe8fdc80f81a93509206c712d1f6363e8df0672ec5425ebb54c90c4988a661e67"
